### ISSUE TITLE
Missing APIs for core types

### ISSUE THREAD

**Issue by raniejade** [godotengine/godot-headers#64] opened 2020-01-24 10:29 UTC
Hello! I'm working on a new native binding for Godot (https://github.com/raniejade/godot-kotlin) and I have notice that there are quite a lot of missing APIs for the core types.

One example is that the getters and setters for `Vector3` are missing, e.g:
- `godot_vector3_get_x`
- `godot_vector3_get_y`
- `godot_vector3_get_z`
- `godot_vector3_set_x`
- `godot_vector3_set_y`
- `godot_vector3_set_z`

I know that there are versioned struct aside from the core one, however, I didn't find the missing APIs there.

**Comment by karroffel** [comment] 2020-01-24 17:36
There is this: https://github.com/GodotNativeTools/godot_headers/blob/57138143b59117c8b0d7471a8e77a75c5b635224/gdnative/vector3.h#L141

**Comment by raniejade** [comment] 2020-01-24 21:36
Interesting, thanks! Another example is for Vector2 (specifically the `project` method). https://docs.godotengine.org/en/latest/classes/class_vector2.html#class-vector2-method-round

**Comment by raniejade** [comment] 2020-01-24 23:19
Another example that is missing: https://docs.godotengine.org/en/latest/classes/class_vector3.html#class-vector3-method-direction-to

**Comment by raniejade** [comment] 2020-01-24 23:32
> There is this:
> 
> https://github.com/GodotNativeTools/godot_headers/blob/57138143b59117c8b0d7471a8e77a75c5b635224/gdnative/vector3.h#L141

@karroffel out of curiosity, why is the API different to `Vector2`? From what I can see `godot_vector3_axis` is not being used outside of `Vector3`, so I don't understand why it exist - a simple getter and setter for `x, y, z` would be more consistent.

**Comment by raniejade** [comment] 2020-01-28 09:23
@karroffel follow up question, how is `api.json` generated? I've seen quite a few inconsistencies in it.
- property types does not match the type of the getter/setter (usually it involves an enum and an int)
- property getter/setter references a virtual method (begins with a `_`). From what I understand virtual methods should not be generated.

**Comment by karroffel** [comment] 2020-01-28 13:13
> out of curiosity, why is the API different to `Vector2`?

There are a lot of functions and they have all been handwritten. I am sure this was just an oversight, I don't recall there being a reasone for something like that.

> how is `api.json` generated? I've seen quite a few inconsistencies in it.

It is autogenerated from the information that Godot's `ClassDB` has. There might be some errors in the generator, but things that you are describing seem like it is just inconsistent data provided to `ClassDB`. Not much to do about it, but bindings can manually clean up some of those inconsistencies (such as `Object::free` being described as `virtual` but that is actually an error), or fix the `_bind_methods()` functions inside Godot.

**Comment by raniejade** [comment] 2020-01-29 06:10
> fix the _bind_methods() functions inside Godot.

I think this should be the right approach, otherwise bindings will have to repeat code for handling those inconsistencies.

**Comment by karroffel** [comment] 2020-01-29 11:58
There is no central place I can point you at. All the classes that have methods with errors also have a `_bind_methods()` function inside the Godot source code. So you need to find the problematic classes and then fix it in the source. Sorry I can't give you much more information than that

**Comment by BastiaanOlij** [comment] 2021-09-27 03:55
I think we can close this issue?

For GDNative take a look at `godot-cpp` where for core classes like Vector2, we've done a re-implementation on the `godot-cpp` side because this is far more efficient than getting/setting members through the API barrier.

For GDExtensions we've done the same but the new `extension_api.json` does include all core types and I can confirm these setters and getters are callable.

All in all, this repo is a mirror of the headers and implementation found in Godot. If after all these years we do wish to have this enhancement added to Godot 3, the issue should be raised in the main Godot repo.

**Comment by akien-mga** [comment] 2021-09-27 07:22
Yes this can be closed. Future issues related to this should be split with one issue per actual problem, so that they can be properly addressed. Inconsistency in the Godot API exposed through ClassDB in the API JSON should be raised at the main Godot repository if they're a bug, or on https://github.com/godotengine/godot-proposals if it would be an enhancement for clarity's sake (e.g. unifying APIs in a way that would make them clearer but break compatibility).

**Closed by akien-mga** 2021-09-27 07:22 UTC
Labels: bug
